# Generated by Django 6.0.3 on 2026-04-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interest",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
