# Generated by Django 6.0.3 on 2026-04-04 01:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_remove_user_linkedin_url_onboardingprefill"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Interest",
            new_name="Topic",
        ),
    ]
