# Generated by Django 6.0.3 on 2026-04-04 01:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_rename_interest_topic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="outreach",
            old_name="interest",
            new_name="topic",
        ),
        migrations.RenameField(
            model_name="requirement",
            old_name="interest",
            new_name="topic",
        ),
    ]
