# Generated by Django 6.0.3 on 2026-04-04 02:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_rename_interest_outreach_topic_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OutreachRequirementResponse",
            new_name="OutreachQuestionResponse",
        ),
        migrations.RenameModel(
            old_name="Requirement",
            new_name="Question",
        ),
    ]
