# Generated by Django 6.0.3 on 2026-04-04 02:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "app",
            "0006_rename_outreachrequirementresponse_outreachquestionresponse_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="outreachquestionresponse",
            old_name="requirement",
            new_name="question",
        ),
    ]
