# Generated by Django 6.0.3 on 2026-04-04 20:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_newtopicprefill"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="prompt",
            new_name="text",
        ),
    ]
