# Generated by Django 6.0.3 on 2026-04-05 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_rename_prompt_question_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutreachAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField()),
                ("score", models.FloatField()),
                ("relevance_score", models.FloatField()),
                ("completeness_score", models.FloatField()),
                ("credibility_score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outreach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.outreach"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutreachAnalysisFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "outreach_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.outreachanalysis",
                    ),
                ),
            ],
        ),
    ]
