# Generated by Django 6.0.3 on 2026-04-05 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_outreachanalysis_outreachanalysisfollowup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outreach",
            name="relevance_reasoning",
        ),
        migrations.RemoveField(
            model_name="outreach",
            name="relevance_score",
        ),
    ]
