# Generated by Django 6.0.3 on 2026-04-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_remove_outreach_relevance_reasoning_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outreachanalysis",
            name="llm_response",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="outreachanalysis",
            name="model_name",
            field=models.CharField(default="", max_length=128),
        ),
    ]
