# Generated by Django 6.0.3 on 2026-04-15 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_outreachanalysis_llm_response_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(default=None, null=True)),
                ("invalidated_at", models.DateTimeField(default=None, null=True)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("requester_ip", models.GenericIPAddressField(default=None, null=True)),
                ("requester_user_agent", models.TextField(default="")),
                ("used_ip", models.GenericIPAddressField(default=None, null=True)),
                ("used_user_agent", models.TextField(default="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
