# Generated by Django 6.0.3 on 2026-04-15 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_alter_usersession_user"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS django_session;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
