# Generated by Django 6.0.3 on 2026-04-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_auto_20260415_1657"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="url_suffix",
            field=models.CharField(
                db_collation="utf8mb4_bin", max_length=136, unique=True
            ),
        ),
    ]
