# Generated by Django 6.0.3 on 2026-04-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_alter_topic_url_suffix"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="closed_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
