# Generated by Django 6.0.3 on 2026-04-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0018_topic_closed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
